name: Validate

on:
  pull_request:
  push:
    branches-ignore:
      - master

permissions: {}

jobs:
  validate:
    if: github.event_name != 'pull_request' && ! github.event.pull_request.head.repo.fork
    name: Lint & Test
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Set up pnpm
        run: corepack enable pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm test:ci

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build
